[general]
import = [
  "~/.config/alacritty/themes/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[window]
opacity = 0.80

[font]
normal = { family = "AdwaitaMono Nerd Font", style = "Regular" }

